apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  containers:
  - name: shell
    image: ubuntu:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    resources:
      requests:
        cpu: 200m
        memory: 500Mi