apiVersion: v1
kind: Service
metadata:
  name: chainlink
  labels:
    app: chainlink
spec:
  clusterIP: None
  selector:
    app: chainlink
  ports:
    - name: listening
      port: 6688
      targetPort: 6688
      protocol: TCP