apiVersion: v1
kind: Service
metadata:
  name: chainlink-polygon
  labels:
    app: chainlink-polygon
spec:
  clusterIP: None
  selector:
    app: chainlink-polygon
  ports:
    - name: listening
      port: 6688
      targetPort: 6688
      protocol: TCP